<?php
/**
 * Created by PhpStorm.
 * User: petwise
 * Date: 11/21/13
 * Time: 9:27 PM
 */

?>

<div id="wrapper">
    <div id="footer">
        <div class="footer_top">
            <div class="container_a">

                <div class="social-icons">
                    <a href="https://www.facebook.com/i.like.wdg" target="_blank" class="roll-fb">Washington DC Web
                                                                                                  Development Company on Facebook</a>
                    <a href="https://twitter.com/wdgtweet" target="_blank" class="roll-tw">Virginia Web Development
                                                                                           Company
                                                                                           on Twitter</a>
                    <a href="http://webdevelopmentgroup.com/feed/" class="roll-rs">DC WordPress Web Development Company.
                                                                                   RSS
                                                                                   Feed</a>
                    <a href="http://www.linkedin.com/company/web-development-group_2?trk=top_nav_home" target="_blank"
                       class="roll-in">Web Development Washington DC company on LinkedIn</a>
                    <a href="http://www.behance.net/wdgdc" target="_blank" class="roll-be">Virginia Web Development
                                                                                           Company
                                                                                           on Behance</a>
                    <a href="https://plus.google.com/117403642763038303446" rel="publisher"></a>
                </div>

            </div>
        </div>
        <div class="footer_bot">
            <div class="container_a">
                <div class="col-left">
                    <a href="http://www.webdevelopmentgroup.com"><img
                            src="./dist/images/footer_image.png"
                            alt="Washington DC Web Development and Design Firm, The Web Development Group Logo"
                            title="Washington DC Web Design Company, The Web Development Group" id="logo-white"/></a>
                </div>
                <!-- /col-left -->
                <div class="col-right">
                    <div id="footer_nav" class="menu-main-menu-container">
                        <ul id="menu-main-menu-1" class="menu">
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-163"><a
                                    title="Services"
                                    href="http://www.webdevelopmentgroup.com/web-development-company-services/">Services</a>
                            </li>
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-80"><a
                                    title="Our Work" href="http://www.webdevelopmentgroup.com/our-work/">Portfolio</a>
                            </li>
                            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-82"><a
                                    title="News" href="http://www.webdevelopmentgroup.com/category/news/">Blog</a></li>
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-93"><a
                                    title="About Us"
                                    href="http://www.webdevelopmentgroup.com/about-web-development-group/">About</a>
                            </li>
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-83"><a
                                    title="Contact" href="http://www.webdevelopmentgroup.com/contact/">Contact</a></li>
                        </ul>
                    </div>
                    <div class="footer-info">
                        <div class="location">
                            <h3>DRIVEN DESIGN CO.</h3>

                            <div>
                                <!--a href="http://goo.gl/maps/QUG8p" target="_blank"><img
                                        src="http://www.webdevelopmentgroup.com/wp-content/themes/thewebdevelopmentgroup/images/map-icon.png"
                                        alt="Washington DC Web Development and Design Firm, The Web Development Group Logo"
                                        title="Washington DC Web Design Company, The Web Development Group" -->
                                <a href="" id="map-icon"/>4002
                                Beechwood Dr.<br/>
                                Columbia, MO 65202</a><br/>
                            </div>
                        </div>
                        <!-- /location -->
                        <div class="in-touch">
                            <h3>GET IN TOUCH</h3>

                            <div>
                                Tel: <a href="tel:+16412262329">1 (641) 226-2329</a><br/>
                                Email: <a href="mailto:info@webdevelopmentgroup.com">contact@drivendesignco.com</a>
                            </div>
                        </div>
                        <!-- /in-touch -->
                        <div class="the-loop">
                            <h3>STAY IN THE LOOP</h3>

                            <div>
                                <form method="post"
                                      action="http://email.address-verify.com/q/V_CdhN_LBw_D0wmxmVZ5vC06gQwK9hYz8">
                                    <input type="hidden" name="crvs"
                                           value="otTQbCiu8gsDOO5-T2LbKKNp438ZIkbz64_3bM9-H1DReVXpP_6iyb4k1IxqJiBBOiN5Rf6QnzA5yN_h7KwQFOQ_dGQvP4mpn0WVfgyu0z4"/>
                                    <table border="0" cellspacing="0" cellpadding="2">
                                        <!--                     <tr>
                                                              <td align="left" colspan="2"><strong>Please fill out the information below</strong></td>
                                                            </tr> -->
                                        <tr style="width: 140px; float: left;">
                                            <!-- <td align="left">Email Address<font color="red"/>*</td> -->
                                            <td><input
                                                    style="width: 140px; height: 31px; color: #ffffff; background: #525252; border: none; padding-left: 15px;"
                                                    type="text" name="email" size="40" maxlength="100"
                                                    value="Email Address"
                                                    onblur="if(this.value == ''){ this.value='Email Address'}"
                                                    onfocus="if (this.value == 'Email Address'){this.value=''}"/></td>
                                            <!-- <input type="text" value="search..." name="s" id="s" onblur="if(this.value == ''){ this.value='search...'}" onfocus="if (this.value == 'search...'){this.value=''}" /> -->
                                        </tr>
                                        <tr style="width: 60px; float: left;">
                                            <td align="left"><input type="submit" id="submit"
                                                                    style="background: url(/dist/images/submit-email.png) no-repeat; text-indent: -9999px; border: none; width: 38px; height: 33px;"
                                                                    value="Sign Up"/></td>
                                        </tr>
                                    </table>
                                </form>
                            </div>
                        </div>
                        <!-- /the-loop -->
                    </div>
                    <!-- /footer-info -->
                </div>
                <!-- /col-riht -->
            </div>
            <!-- /container -->
        </div>
        <!-- /footer-bot -->
        <div class="footer-bottom-links">
            <div class="container_b">
                <div class="bottom_copy">
                    &copy;2013 Driven Design Co. All Rights Reserved.
                </div>

            </div>
            <!-- /container -->
        </div>
        <!-- /footer-bottom-links -->

        <!-- End Footer -->
    </div>
</div>
<!-- /.wrapper -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="../dist/js/bootstrap.min.js"></script>
</body>
</html>