<?php
/**
 * Created by PhpStorm.
 * User: petwise
 * Date: 11/21/13
 * Time: 9:21 PM
 */

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

        <title>Driven Design Co.- Home</title>

        <!-- Bootstrap core CSS -->
        <link href="../dist/css/bootstrap.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]>
        <script src="../../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- Custom styles for this template -->
        <link href="../carousel.css" rel="stylesheet">
        <link href="../navbar-static-top.css" rel="stylesheet">
        <style type="text/css">

            .jumbotron {
                position: relative;
                z-index: 3;
                height: 500px;
                background: linear-gradient(rgba(255, 255, 255, 1), rgba(255, 255, 255, 0), rgba(255, 255, 255, 1)), url('../dist/images/tag_cloud4.png') no-repeat center;
            }

        </style>
    </head>